config/routes.rb
AwesomeHome::Application.routes.draw do

  get 'about' => 'site#about'
  get 'pricing' => 'site#pricing'
  get 'contact' => 'inquiries#new'
  get 'signup' => 'signups#new'

  get 'signup_confirmed' => 'site#signup_confirmed'
  get 'inquiry_confirmed' => 'site#inquiry_confirmed'

  get 'offers/trial1' => 'offers#trial1'
  get 'offers/trial2' => 'offers#trial2'
  get 'offers/trial3' => 'offers#trial3'
  get 'offers/trial4' => 'offers#trial4'
  get 'offers/trial5' => 'offers#trial5'

  resources :signups, :only => [:new, :create]
  resources :inquiries, :only => [:new, :create]

  root :to => "site#index"

  get '*path' => 'site#not_found'

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  validates :name, :presence => true
  validates :email, :presence => true
  validates :subject, :presence => true
  validates :message, :presence => true

  after_create :send_email

  def send_email!
    GeneralMailer.new_inquiry(self).deliver
  end

  protected

  def send_email
    send_email!
  rescue Exception => e
    nil
  end

end

app/models/signup.rb
class Signup < ActiveRecord::Base

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
#  validates :company, :presence => true
#  validates :subdomain, :presence => true

  after_create :send_email

  def send_email!
    GeneralMailer.signup_request(self).deliver
  end

  protected

  def send_email
    send_email!
  rescue Exception => e
    nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActionController::RoutingError, :with => :render_not_found
  rescue_from ActionController::UnknownAction, :with => :render_not_found
  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found

  protected

  def render_not_found
    render 'site/not_found', :status => :not_found
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @on_contact = true
    @inquiry = Inquiry.new
  end

  def create
    @on_contact = true
    @inquiry = Inquiry.new params[:inquiry]
    if @inquiry.save
      redirect_to inquiry_confirmed_path
    else
      render :new
    end
  end


end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  layout 'offers'

  caches_page :trial1, :trial2, :trial3, :trial4, :trial5


end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

  def new
    @signup = Signup.new
    @on_signup = true
  end

  def create
    @on_signup = true
    @signup = Signup.new params[:signup]
    if @signup.save
      redirect_to signup_confirmed_path
    else
      render :new
    end
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  caches_page :index, :about, :pricing, :contact, :signup_confirmed, :inquiry_confirmed


  def index
    @on_home = true
  end

  def not_found
  end
  
  def about
    @on_about = true
  end

  def pricing
    # raise ActiveRecord::RecordNotFound
    @on_pricing = true
  end

  def contact
    @on_contact = true
  end

  def signup_confirmed
    @on_signup = true
  end

  def inquiry_confirmed
    @inquiry = Inquiry.new params[:inquiry]
    @on_contact = true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def phone_number
    "1-888-783-1438"
  end

  def n
    raw "<span class='name'>Span6</span>"
  end

  def check
    raw '<img src="images/check.png" alt="Included" />'
  end

  def x
    raw '<img src="images/x.png" alt="Not Included" />'
  end

end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/inquiries/_form.html.erb
<% form_for @inquiry  do |f| %>

  <%= render 'shared/error_messages_list', :object => @inquiry, :heading => "Please address the following issues and try again:"   %>

  <p>
    <label>Your Name</label>
    <%= f.text_field :name, :class => "text_field required" %>
  </p>

  <p>
    <label>Your Email</label>
    <%= f.text_field :email, :class => "text_field required" %>
  </p>

  <p class="last">
    <label>Subject</label>
    <%= f.select :subject, ['General Support', 'Feedback', 'Inquiry', 'Other'], {}, :class => "text_field"  %>
    <!--<select name="subject" id="subject" class="text_field">
      <option value="General Support">General Support</option>
    </select>-->
  </p>
  <div class="clear"></div>

  <p class="message">
    <label>Message</label>
    <%= f.text_area :message, :class => "text_field" %>
    <!--<textarea name="message" id="message" class="text_field" rows="" cols=""></textarea>-->
  </p>

  <div class="send_form">
    <a href="javascript:;" class="button submit" id="send"><span>Submit</span></a>
  </div>
  <div class="clear"></div>

<% end  %>

app/views/inquiries/new.html.erb
<div class="header page">
  <h1>Contact Us</h1>
  <ul>
    <li><a href="#"><%= phone_number %></a></li>
  </ul>
</div>

<div id="contact" class="padding">

  <p>If you'd like to arrange for a Demo and a Free Trial, simply <a href="/signup">sign-up here</a></p>
  <p>Want to talk to us right away? Call us toll-free at: <strong><%= phone_number %></strong></p>
  <p>For any other inquiries, questions or requests, please submit the form below:</p>

  <div class="section_title">
    <h3>Other Inquiry</h3>
  </div>

  <p class="validation">Bla bla</p>

  <%= render 'form' %>

</div>

app/views/layouts/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5190526-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Span6 - Powerful campaign, affiliate and customer management.</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Span6 is powerful campaign, affiliate and customer management platform that enabling advertisers to channel traffic from their media partners into multiple landing pages, convert the visitors into leads or customers, and track the performance of the overall flow." />
    <meta name="keywords" content="Landing page integration,lead generation,e-commerce,affiliate marketing,campaigns,offers,split testing,landing pages,fraud detection,merchant accounts,payment gateways,crm" />
    <%= stylesheet_link_tag 'styles', '/javascripts/fancybox/jquery.fancybox-1.3.4.css', 
      'green-blue', '/mediaelement/mediaelementplayer.css', :cache => "cache/site" %>
    <%= javascript_include_tag 'jquery', 'jquery.tools', 'fancybox/jquery.fancybox-1.3.4.pack',
      'rails', 'application', 'site','detectmobilebrowser','/mediaelement/mediaelement-and-player.min.js', :cache => 'cache/site' %>

    <%= render 'layouts/ga'  if Rails.env.production? %>
  </head>
  <body>
    <div id="header">
      <div class="page">
        <a href="/" class="logo">Span6</a>
        <ul>
          <li<%= raw ' class="active"' if @on_home %>><a href="/">Home</a></li>
          <li<%= raw ' class="active"' if @on_about %>><a href="/about">About</a></li>
          <li<%= raw ' class="active"' if @on_signup %>><a href="/signup">Demo</a></li>
          <!--<li<%= raw ' class="active"' if @on_pricing %>><a href="/pricing">Pricing</a></li>-->
          <li<%= raw ' class="active"' if @on_contact %>><a href="/inquiries/new">Contact</a></li>
          <li><a href="/inquiries/new">1-888-783-1438</a></li>
        </ul>
        <div class="clear"></div>
      </div>
    </div>

    <div id="page">
      <div class="top"></div>
      <div class="content">
        <%= yield %>
      </div>
      <div class="bottom"></div>
    </div>

    <div id="footer" class="page">
      <p>&copy; 2011 <%= link_to 'Span Six Software', 'http://www.spansix.com/' %>. <%= n %>, Marketing automation made simple.</p>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/signup">Demo</a></li>
        <!--<li><a href="/pricing">Pricing</a></li>-->
        <li><a href="/contact">Contact</a></li>
        <li><a href="/contact">1-888-783-1438</a></li>
      </ul>
      <div class="clear"></div>
    </div>

    <%= yield :js %>
  </body>
</html>

app/views/layouts/offers.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Span6 - Powerful campaign, affiliate and customer management.</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Span6 is powerful campaign, affiliate and customer management platform that enabling advertisers to channel traffic from their media partners into multiple landing pages, convert the visitors into leads or customers, and track the performance of the overall flow." />
    <meta name="keywords" content="Landing page integration,lead generation,e-commerce,affiliate marketing,campaigns,offers,split testing,landing pages,fraud detection,merchant accounts,payment gateways,crm" />
    <%= stylesheet_link_tag 'styles', '/javascripts/fancybox/jquery.fancybox-1.3.4.css',
      'green-blue', '/mediaelement/mediaelementplayer.css', :cache => "cache/site" %>
    <%= javascript_include_tag 'jquery', 'jquery.tools', 'fancybox/jquery.fancybox-1.3.4.pack',
      'rails', 'application', 'site','detectmobilebrowser','/mediaelement/mediaelement-and-player.min.js', :cache => 'cache/site' %>

    <%= render 'layouts/ga'  if Rails.env.production? %>
  </head>
  <body>
    <div id="header">
      <div class="page">
        <a href="/" class="logo" onclick="return false;">Span6</a>
        <div class="clear"></div>
      </div>
    </div>

    <div id="page">
      <div class="top"></div>
      <div class="content">
        <%= yield %>
      </div>
      <div class="bottom"></div>
    </div>

    <div id="footer" class="page">
      <p>&copy; 2011 <%= 'Span Six Software' %>. <%= n %>, Marketing automation made simple.</p>
      <ul>
        <li><strong>Call us for a FREE consultation, demo and trial at 1-888-783-1438</strong></li>
      </ul>
      <div class="clear"></div>
    </div>

    <%= yield :js %>
  </body>
</html>

app/views/offers/_shared.html.erb
<%= javascript_include_tag 'jquery.scrollto-min', 'jquery.validate' %>
<script type="text/javascript" charset="utf-8">
  var player = null;
  $(document).ready(function() {
    // Configure fancybox plugin
    var os = detectMobile(navigator.userAgent);
    if (os.android) {
      var html = '<video poster="/images/s6-video-poster-v3.png" src="/s6-home-video-cut4.hero.mp4" width="960" height="568" controls="controls" preload="true">';
      $('#videocontainer').html(html);
    } else if (os.blackberry) {
      var html = '<video poster="/images/s6-video-poster-v3.png" src="/s6-home-video-cut4.mobile.3gp" width="960" height="568" controls="controls" preload="true">';
      $('#videocontainer').html(html);
    } else if (os.iphone) {
      var html = '<video poster="/images/s6-video-poster-v3.png" src="/s6-home-video-cut4.iphone.m4v" width="960" height="568" controls="controls" preload="true">';
      $('#videocontainer').html(html);
    } else {
      if ($('video').size() > 0) {
        player = new MediaElementPlayer('video',{
          defaultVideoWidth: 960,
          defaultVideoHeight: 568,
          pluginPath: '/mediaelement/'
        });
      }
    }

    $('a.scrollto').click( function(e) {
      var anchor = $(this).data('anchor');
      e.stopPropagation();
      $.scrollTo( anchor , 600);//, {easing:'elasout'} );
      return false;
    });

  });
</script>


<script>
  function trackLead() {
    osm_tracker.track({
      lead: {
        'first_name': $('#first_name').val(),
        'last_name': $('#last_name').val(),
        'email': $('#email').val(),

        'address[phone1]': $('#phone').val(),

        'custom[company]': $('#company').val(),
        'custom[notes]': $('#notes').val()
      }
    });
  }

  function formSubmit() {
    trackLead();
    $('#contact-form').hide();
    $('#success-message').show();
    $('#edit-request').show();
    return false;
  }

  $(function() {
    $('.text_field').blur(function(e) {
      trackLead();
    });
    $('#edit-request').click(function() {
      $('#contact-form').show();
      $('#edit-request').hide();
      return false;
    });
    $('form').validate({
      errorContainer: '#message-box',
      errorLabelContainer: '#message-box ul',
      wrapper: 'li',
      errorElement: 'em',
      submitHandler: function(form) {
        formSubmit();
      },
      rules: {
        // simple rule, converted to {required:true}
        name: "required",
        // compound rule
        email: {
          required: true,
          email: true
        },
        'address[phone1]': {
          required: true
        }
      },
      messages: {
        first_name: "Please specify your first name, to avoid an awkward initial contact",
        last_name:  "Please specify your last name, to avoid an awkward initial contact",
        email: {
          required: "We need your email address to contact you (and nothing more, promise.)",
          email: "Your email address must be in the format of name@domain.com"
        },
        'address[phone1]': {
          required: "We need your phone number to contact you (and nothing more, promise.)"
        }
      }
    });
  });
</script>

app/views/shared/_error_messages_list.html.erb
<% message_replacements ||= {} %>
<% heading ||= nil %>
<% hidden ||= false %>

<% if object.errors.any? %>
  <div class="validation" style="<%= "display:none" if hidden %>">
    <div>
      <strong>
        <% if heading %>
          <%= heading %>
        <% else %>
          Could not <%= object.new_record? ?  'create' : 'update' %> <%= object.class.to_s.underscore.humanize %> due to the following <%= pluralize(object.errors.count, "error") %>:
        <% end %>
      </strong>
      <ul>
        <% messages = [] %>
        <% object.errors.full_messages.each do |msg| %>
          <% if to_replace = message_replacements.keys.detect {|k| msg.starts_with?(k) }  %>
            <% messages <<  message_replacements[to_replace] %>
          <% else %>
            <% messages << msg %>
          <% end %>
        <% end %>
        <% messages.uniq.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/signups/_form.html.erb
<% form_for @signup do |f| %>

  <%= render 'shared/error_messages_list', :object => @signup, :heading => "Please address the following issues and try again:"   %>

  <h2><span>Required Info</span></h2>

  <p>
    <label>First Name</label>
    <%= f.text_field :first_name, :class => "text_field required" %>
  </p>

  <p>
    <label>Last Name</label>
    <%= f.text_field :last_name, :class => "text_field required" %>
  </p>

  <p>
    <label>E-mail Address</label>
    <%= f.text_field :email, :class => "text_field required email" %>
  </p>

  <div class="clear margin"></div>

  <h2><span>Optional Info</span></h2>


  <p>
    <label>Phone Number</label>
    <%= f.text_field :phone_number, :class => "text_field" %>
  </p>


  <p>
    <label>Company</label>
    <%= f.text_field :company, :class => "text_field required" %>
  </p>

  <p>
    <label>Notes</label>
    <%= f.text_area :notes, :size => "5x5", :class => "text_field", :style=>"width:248px;height:80px;" %>
  </p>

  <div class="clear"></div>

  <div class="send_form">
    <a href="javascript:;" class="button submit"><span>Complete Signup</span></a>
    <span class="trial">No obligations. We will contact you to setup a demo.</span>
  </div>
<% end %>

app/views/signups/_right_side.html.erb
<div class="sidebar_box">
  <h4>Signup Instructions</h4>
  <p>
    Please fill out the form so that our technical experts can contact you for a Demo.
    We will attempt to contact you by phone and if unsuccessful or not provided, then by email.
  </p>
</div>

<div class="sidebar_box">
  <h4>Compatible Browsers</h4>
  <ul>
    <li>Firefox 3 or later</li>
    <li>Safari 4 or later</li>
    <li>Chrome 6 or later</li>
    <li>Opera 10 or later</li>
    <li>IE 8 or later</li>
  </ul>
</div>

<div class="sidebar_box">
  <h4>Contact Us</h4>
  <p>Still have questions? <a href="/contact">Contact us</a>.</p>
</div>

app/views/signups/new.html.erb
<div class="header page">
  <h1>Signup For A Demo</h1>
</div>

<div id="signup" class="padding">

  <div class="left" id="thankyoucontainer" style="display:none">
    <h2><span>Thank You</span></h2>
    <p>Thank you for your interest. We will be contacting you within the next business day.</p>
  </div>

  <div class="left" id="formcontainer">
    <%= render 'form' %>
  </div>

  <div class="right">
    <%= render 'right_side' %>
  </div>
  <div class="clear"></div>

</div>

app/views/site/about.html.erb
<div class="header page">
  <h1>About Us</h1>
  <!--
  <ul>
    <li><a href="html_elements.html">HTML Elements</a></li>
    <li><a href="2_column.html">2 Column</a></li>
  </ul>
  -->
</div>

<div id="about" class="padding">

  <div class="wrap_image_left">
    <img src="images/about_img1.png" alt="" />
  </div>

  <p>
    <%= n %> is a new cutting-edge platform that enables online advertisers to easily channel traffic from affiliate campaigns into multiple landing pages, convert the visitors into leads or customers, and track the performance of the overall flow.
  </p>
  <p>
    What's exciting is that this is merely one aspect of the ever growing platform that is <%= n %>.
    <br/>
    <% if false %>
      <a href="/signup">Signup</a> now for a free one-on-one or conference-based Demo to truly see all that you'll be able to do with <%= n %>.
    <% end %>
  </p>
<br/>
  <a href="<%= new_signup_path %>" class="button icon"><img src="/images/go_icon.png" alt="" /><span>View our demo</span></a>
  <span class="trial">Or call us directly at <%= phone_number %>.</span>

  <div class="clear"></div>
  <br/>

  <div class="section_title">
    <h3>Our Leadership Team</h3>
  </div>

  <!-- Start Team Member -->
  <div class="team member_left">
    <h3>Khurram Virani <span>Lead Developer</span></h3>
    <img src="/images/kv_small.png" alt="Khurram Virani" />
    <p>
      Khurram has been involved in the Affiliate Marketing industry for over five years.
      Having worked on other Affiliate Marketing platforms in the past, he learned the problems and shortcomings in the software.
      This insight was used when creating <%= n %>.
    </p>
    <ul>
      <li><a href="http://www.twitter.com/viranik">Twitter</a></li>
      <li><a href="http://www.linkedin.com/in/kvirani">LinkedIn</a></li>
    </ul>
  </div>
  <!-- End Team Member -->

  <!-- Start Team Member -->
  <div class="team member_right">
    <h3>Farida Ali <span>Financial Officer</span></h3>
    <img src="/images/fa_small2.png" alt="Farida Ali" />
    <p>
      Farida Ali is a young and exciting BBA and MBA. While demanding,
      Farida creates a strong work environment and makes everyone around her more successful at their jobs.
      Her expertise is of great use at Span6 as she manages all of the financial and operational aspects of the company.
    </p>
    <ul>
      <li><a href="http://www.faridaali.com">Personal</a></li>
      <li><a href="http://twitter.com/farida_ali">Twitter</a></li>
      <li><a href="http://www.linkedin.com/in/faridaali">LinkedIn</a></li>
    </ul>
  </div>
  <!-- End Team Member -->

  <div class="clear"></div>

  <!-- Start Team Member -->
  <div class="team member_left">
    <h3>Tyler Ginn <span>Business Development Manager</span></h3>
    <img src="/images/tg_small.jpg" alt="Tyler Ginn" style="height: 126px; width: 125px" />
    <p>
      Tyler Ginn is the newest addition to the Span6 team.
      He uses diverse skills and background to help with sales, marketing and other business development strategies to take Span6 to its next level.
    </p>
    <ul>
      <li><a href="http://twitter.com/span_six">Twitter</a></li>
      <li><a href="http://ca.linkedin.com/pub/tyler-ginn/30/219/7b3">LinkedIn</a></li>
    </ul>
  </div>
  <!-- End Team Member -->

  <div class="clear"></div>
</div>

app/views/site/not_found.html.erb
<div class="header page">
  <h1>Page not Found (404)</h1>
  <!--<ul>
    <li class="active"><a href="tour.html">Overview</a></li>
    <li><a href="tour.html">My Account</a></li>
  </ul>-->
</div>

<div id="tour" class="padding">


  <p>The page you are looking for no longer exists. <br/>
    Sorry for the inconvenience</p>


</div>

app/views/site/pricing.html.erb
<div class="header page">
  <h1>Plans &amp; Pricing</h1>
</div>

<!-- Start Price Table -->
<div id="pricing" class="padding">

  <div id="row_names">
    <ul>
      <li>Set-up Fee</li>
      <li>Monthly Fee</li>
      <li>Transaction Fee</li>
      <li>Customization Hours</li>
      <li>Max Users</li>
      <li>Storage</li>
      <li>Bandwidth</li>
      <li>Max SKUs</li>     
      <li>Max Landing Pages</li>
      <li>Recurring Billing</li>
      <li>Affiliate Logins</li>
      <li>Real-Time Stats</li>
      <li>SSL Checkout</li>
      <li>SSL Admin</li>
      <li>Fraud Detection</li>

      <li>Custom Domains</li>

    </ul>
  </div>

  <div id="price_table">
    <table cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <td>
            <h2>Start Up</h2>
            <span>A Great Way To Try It Out</span>
          </td>
          <td>
            <h2>Professional</h2>
            <span>For Small Companies</span>
          </td>
          <td>
            <h2>Commercial</h2>
            <span>For Mid-sized Companies</span>
          </td>
          <td class="last">
            <h2>Enterprise</h2>
            <span>For Large Organizations</span>
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>$1,000</td>
          <td>$1,600</td>
          <td><%= link_to 'Contact Us', contact_path %></td>
          <td class="last"><%= link_to 'Contact Us', contact_path %></td>
        </tr>
        <tr class="color">
          <td>$500</td>
          <td>$1,200</td>
          <td><%= link_to 'Contact Us', contact_path %></td>
          <td class="last"><%= link_to 'Contact Us', contact_path %></td>
        </tr>
        <tr>
          <td>$0.95</td>
          <td>$0.40</td>
          <td><%= link_to 'Contact Us', contact_path %></td>
          <td class="last"><%= link_to 'Contact Us', contact_path %></td>
        </tr>
        <tr class="color">
          <td>0</td>
          <td>5</td>
          <td>10</td>
          <td class="last">15</td>
        </tr>
        <tr>
          <td>3</td>
          <td>10</td>
          <td>25</td>
          <td class="last">Unlimited</td>
        </tr>
        <tr class="color">
          <td>3 GB</td>
          <td>3 GB</td>
          <td>5 GB</td>
          <td class="last">20 GB</td>
        </tr>
        <tr>
          <td>3 GB</td>
          <td>3 GB</td>
          <td>5 GB</td>
          <td class="last">20 GB</td>
        </tr>
        <tr class="color">
          <td>Unlimited</td>
          <td>Unlimited</td>
          <td>Unlimited</td>
          <td class="last">Unlimited</td>
        </tr>
        <tr>
          <td>Unlimited</td>
          <td>Unlimited</td>
          <td>Unlimited</td>
          <td class="last">Unlimited</td>
        </tr>
        <tr class="color">
          <td><%= check %></td>
          <td><%= check %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr>
          <td><%= check %></td>
          <td><%= check %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr class="color">
          <td><%= check %></td>
          <td><%= check %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr>
          <td><%= check %></td>
          <td><%= check %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr class="color">
          <td><%= x %></td>
          <td><%= check %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr> 
        <tr>
          <td><%= x %></td>
          <td><%= x %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr class="color">
          <td><%= x %></td>
          <td><%= x %></td>
          <td><%= check %></td>
          <td class="last"><%= check %></td>
        </tr>
        <tr class="buttons">
          <td><%= link_to '<img src="/images/go_icon.png" /><span>Request a Demo</span>'.html_safe, new_signup_path, :class => "button icon" %></td>
          <td><%= link_to '<img src="/images/go_icon.png" /><span>Request a Demo</span>'.html_safe, new_signup_path, :class => "button icon" %></td>
          <td><%= link_to '<img src="/images/go_icon.png" /><span>Request a Demo</span>'.html_safe, new_signup_path, :class => "button icon" %></td>
          <td><%= link_to '<img src="/images/go_icon.png" /><span>Request a Demo</span>'.html_safe, new_signup_path, :class => "button icon" %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clear"></div>
  <!-- End Price Table -->

  <!-- Start FAQs -->
  <div id="faq">

    <div class="section_title">
      <h3>Pricing FAQ's</h3>
    </div>

    <div class="left">
      <h4>Can I cancel anytime?</h4>
      <p>We will do our very best to make sure that your CRM and Affiliate Marketing needs are met.
        <%= n %> is built with customization and flexibility in mind.
      </p>
      <p>If however you still want to cancel your account with us, we will make that as quick and painless as humanly possible.</p>

    </div>

    <div class="right">
      <h4>Is there a free trial?</h4>
      <p>Setting up a new <%= n %> account requires developer and management's time.
        Requirements have to be understood and features customized.
      </p>
      <p>For these and other reasons, we cannot currently offer a free trial.
        However, please call us at <%= phone_number %> to arrange for a one-on-one or conference-based demo
      </p>
    </div>
    <div class="clear"></div>

    <div class="left">
      <h4>I’m not sure one of your pre-made plans is for us.</h4>
      <p>Every company has different needs. Let us know, and we can customize a plan that suits your unique needs. We're always willing to work with our clients to help them get exactly the experience they desire.
      </p>
    </div>

    <div class="right">
      <h4>Is it easy to switch plans?</h4>
      <p>Absolutely. Switch your plan at any time and your monthly bill will be pro-rated. You don't have to wait for the next billing cycle to switch plans and you will never pay extra for switching your plan during a billing cycle.
      </p>
    </div>

    <div class="clear"></div>

    <div class="left">
      <h4>I already have a CRM but yours is SO much better!</h4>
      <p>
        We know. And we also know that moving your existing data can be a daunting thought.
        But fear not, give us a call and we will work with you and your existing CRM provider to import your data into <%= n %>.
      </p>
    </div>

    <div class="right">
      <h4>Our Expenses are tight, can we work around that?</h4>
      <p>Please <%= link_to 'contact us', contact_path %>. We're willing to work with you to provide a custom plan that will suit your needs as well as your budget.</p>
    </div>

    <div class="clear"></div>


  </div>

</div>
<!-- End FAQs -->